### ISSUE TITLE
visualization of saliency maps is barely visible

### ISSUE THREAD

**Issue by nikparth** [serre-lab/Harmonization#10]
Hi I tried to run the code for the resnet50 and harmonized resnet and generate saliency maps. The scores seem fine (0.34 --> 0.45) but when I try to visualize the maps, all I get are very small ranges so the maps are barely visible. Is this expected? or did you do some kind of normalization before visualization.

**Comment by fel-thomas** [comment]
Hello ;) 
thank you for taking the time to open an issue. To visualize the heatmaps, we commonly use Matplotlib. 
Here is a code snippet that should display the image and associated explanations:

```
plt.imshow(img)

if len(heatmap.shape) == 4:
   heatmap = np.mean(heatmap, -1) # mean over rgb channel

plt.imshow(heatmap, cmap='jet', alpha=0.5)
plt.show()
```

Please let me know if you have any other issues.
