### ISSUE TITLE
Unexpected alignment scores on harmonized models

### ISSUE THREAD

**Issue by niniack** [serre-lab/Harmonization#8]
I am having trouble with evaluating the harmonized models with `evaluate_clickme()`. 

For the ResNet50 model, the Keras provided pre-trained weights (with an evaluation on 500 validation images) results in an alignment score of 0.35. The harmonized ResNet 50 results in 0.14. 

For the ViT_B16 model, with 50 validation images, the pre-trained weights results in a score of 0.023, whereas the harmonized ViT returns a score of -0.180. 

What I am running:

```python
import numpy as np
import torch
import torchvision
from torchvision import transforms
from vit_keras import vit
import timm
import tensorflow as tf
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

from harmonization.common import load_clickme_val
from harmonization.evaluation import evaluate_clickme
from harmonization.models import load_ResNet50, load_ViT_B16

base_model = vit.vit_b16(
        image_size=224,
        activation='linear',
        pretrained=True,
        include_top=True,
        pretrained_top=True
    )

#GPU limitation
clickme_dataset = load_clickme_val(batch_size = 2)

scores = evaluate_clickme(base_model,
                          clickme_val_dataset=clickme_dataset.take(50))

print(scores['alignment_score'])


harmonized_model = load_ViT_B16()

scores = evaluate_clickme(harmonized_model,
                          clickme_val_dataset=clickme_dataset.take(50))
print(scores['alignment_score'])

```

- I am not sure why the harmonized results result in a lower alignment score? My intuition is that the higher the alignment, the "better"?
- What does it mean for an alignment score to be negative?
- According to Fig 3 in the paper, it seems the ViT should perform significantly better than ResNet, yet here the results don't reflect that

Thanks!

**Comment by drewlinsley** [comment]
Your insights are correct: positive alignment is better, harmonized models have higher alignment than unharmonized models, and the harmonized ViT was significantly more aligned with humans than any other model tested.

Tagging @fel-thomas to dig into this. Thanks, @niniack!

**Comment by fel-thomas** [comment]
Hello @niniack, and thank you for your interest in the library! :)

It looks like you are using the `evaluate_clickme` function to evaluate the performance of your models on the ClickMe dataset. In order to use this function, you need to specify a preprocessing function that will be applied to the images in the dataset before they are passed through the model. 

All our harmonized model have the exact same preprocessing function. You can import it using 
```
from harmonization.models import preprocess_input
``` 

Then use it as a parameter in your evaluation loop:

```python
scores = evaluate_clickme(model, clickme_val_dataset, preprocess_inputs=preprocess_input)
```
I re-run the code to be sure and I found `scores['alignment_score'] > 0.72` on my side.
Don't hesitate if you have more questions!  

@drewlinsley do you think I should raise a warning when no preprocessing is specified ?

**Comment by niniack** [comment]
Hey @drewlinsley, @fel-thomas, 

Thanks for your quick responses! 

After passing in the `preprocess_input` method, I am able to reproduce the alignment scores from Figure 3 for Resnet50 and ViT.

If I may suggest something, I think it would be helpful to make it a bit more explicit on [this page](https://serre-lab.github.io/Harmonization/evaluation/). There is mention of some `preprocessing_function` but I wasn't able to determine that I needed to import a specific method for the ClickMe dataset.
