### ISSUE TITLE
Clickme Dataset 

### ISSUE THREAD

**Issue by niniack** [serre-lab/Harmonization#9]
Hi, 

This is a very cool project! It's wonderful for you to share and organize your work :) 

Is there a painless way to access the ClickMe dataset used in this project? 

I see the data is stored as .tfrecord files. I am looking to work with Pytorch and want to avoid the conversion from .tfrecord to however I end up using it in pytorch.

**Comment by drewlinsley** [comment]
You can find per-image npzs here:
https://connectomics.clps.brown.edu/tf_records/clicktionary_files/

**Comment by niniack** [comment]
Thanks!
